name: Build & Deploy to Dev on Hetzner

on:
  push:
    branches: [develop]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4.1.7

      - name: "Build and push image"
        uses: azure/docker-login@v2
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build -f Dockerfile . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/alkemio-kratos-webhooks:${{ github.sha }} -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/alkemio-kratos-webhooks:latest
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/alkemio-kratos-webhooks:${{ github.sha }}

      - name: Install Kubectl
        uses: azure/setup-kubectl@v4.0.0
        with:
          version: "v1.27.6"

      - name: Set up Kubeconfig for Hetzner k3s
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_SECRET_HETZNER_DEV }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Create Image Pull Secret
        run: |
          kubectl create secret docker-registry alkemio-kratos-webhooks-secret \
            --docker-server=${{ secrets.REGISTRY_LOGIN_SERVER }} \
            --docker-username=${{ secrets.REGISTRY_USERNAME }} \
            --docker-password=${{ secrets.REGISTRY_PASSWORD }} \
            --dry-run=client -o yaml | kubectl apply -f -

      - uses: Azure/k8s-deploy@v5.0.0
        with:
          manifests: |
            manifests/25-kratos-webhooks-deployment-dev.yaml
          images: |
            ${{ secrets.REGISTRY_LOGIN_SERVER }}/alkemio-kratos-webhooks:${{ github.sha }}
          imagepullsecrets: |
            alkemio-kratos-webhooks-secret
